name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Check Tests
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: testomatio/check-tests@stable
      with:
        framework: protractor
        tests: e2e/test-suites/*.e2e-spec.ts
        token: ${{ secrets.GITHUB_TOKEN }}
        typescript: true
