name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Check Tests
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Run tests
      run: |
          npm install
          node node_modules/protractor/bin/webdriver-manager update
          npm run e2e
