name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Check Tests
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Run tests
      run: |
          cd CourtRoom_RemoteCounsel
          npm run e2e
